repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    set:
      - name: image.tag
        value: 3.5.2
      - name: listeners.client.protocol
        value: SASL_PLAINTEXT
      - name: listeners.interBroker.protocol
        value: SASL_PLAINTEXT
      - name: broker.replicaCount
        value: 5

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    set:
      - name: image.tag
        value: latest
      - name: listeners.client.protocol
        value: PLAINTEXT
      - name: listeners.client.sslClientAuth
        value: none
      - name: listeners.interBroker.protocol
        value: PLAINTEXT
      - name: listeners.interbroker.sslClientAuth
        value: none
      - name: broker.replicaCount
        value: 1